---

- name: rockylinux8
  image: geerlingguy/docker-rockylinux8-ansible:latest
- name: oraclelinux8
  image: dropveter/oraclelinux8-ansible
- name: almalinux8
  image: dropveter/almalinux8-ansible
- name: debian11
  image: geerlingguy/docker-debian11-ansible:latest
- name: ubuntu2004
  image: geerlingguy/docker-ubuntu2004-ansible:latest
