---

- name: Download the latest code
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Extract code to /tmp
  unarchive:
    src: /tmp/latest.tar.gz
    dest: "{{ wordpress_tmp_path | dirname }}"
    remote_src: yes
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"

- name: Copy config file from template
  copy:
    src: "{{ wordpress_tmp_path }}/wp-config-sample.php"
    dest: "{{ wordpress_tmp_path }}/wp-config.php"
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
    mode: "0644"
    remote_src: true
    force: false

- name: Edit config with DB settings
  lineinfile:
    path: "{{ wordpress_tmp_path }}/wp-config.php"
    line: "define('{{ item.key }}', '{{ item.value }}');"
    regexp: "define.*'{{ item.key }}',.*"
    state: present
  loop:
    - key: 'DB_HOST'
      value: '{{ wordpress_db_host }}'
    - key: 'DB_NAME'
      value: '{{ wordpress_db_name }}'
    - key: 'DB_USER'
      value: '{{ wordpress_db_user }}'
    - key: 'DB_PASSWORD'
      value: '{{ wordpress_db_pwd }}'

- name: Setup access using htaccess
  copy:
    src: files/htaccess
    dest:  "{{ wordpress_tmp_path }}/.htaccess"
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
    mode: "0644"

- name: Rsync data
  synchronize:
    src: "{{ wordpress_tmp_path }}/"
    dest: "{{ wordpress_path }}"
    rsync_opts:
      - "--omit-dir-times"
  delegate_to: "{{ inventory_hostname }}"
  notify: Restarting web service
  # tags: molecule-idempotence-notest

- name: Change SELinux context
  sefcontext:
    target: "{{ wordpress_path }}"
    setype: httpd_sys_rw_content_t
    state: present
  notify: Restarting web service
  when:
    - ansible_selinux is defined
    - ansible_selinux['status'] == 'enabled'

- name: Reset configuration path
  set_fact:
    wordpress_conf_dir: "{{ wordpress_path }}"
