---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    openssl_fqdn: www.example.com
    apache_fqdn: server.example.com
    apache_ssl_key: "{{ openssl_server_key }}"
    apache_ssl_crt: "{{ openssl_server_crt }}"
    apache_ssl_chain: "{{ openssl_server_crt }}"
    apache_vhosts: "[{'vhost': 'www.example.com', 'template': 'vhost.conf.j2', 'listen': '*', 'port': '443', 'ssl': True, 'ssl_key': '{{ openssl_server_key }}', 'ssl_crt': '{{ openssl_server_crt }}', 'ssl_chain': '{{ openssl_server_crt }}', 'owner': '{{ apache_user }}', 'group': '{{ apache_group }}'}]"
    mariadb_user: root
    mariadb_pwd: root
    mariadb_db_host: localhost
    mariadb_db_name: wordpress
    mariadb_db_user: wordpress
    mariadb_db_pwd: wordpress
    mariadb_socket_authentication: False
    wordpress_path: /var/www/www.example.com/public_html
    wordpress_conf_dir: /var/www/www.example.com/public_html
    wordpress_db_host: localhost
    wordpress_db_name: wordpress
    wordpress_db_user: wordpress
    wordpress_db_pwd: wordpress
  roles:
    - openssl
    - apache
    - php
    - mariadb
  tasks:
    - name: Include role 'ansible-role-wordpress'
      ansible.builtin.include_role:
        name: ansible-role-wordpress
