---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    openssl_fqdn: server.example.com
    apache_fqdn: server.example.com
    apache_ssl_key: "{{ openssl_server_key }}"
    apache_ssl_crt: "{{ openssl_server_crt }}"
    apache_ssl_chain: "{{ openssl_server_crt }}"
    mariadb_user: root
    mariadb_pwd: root
    mariadb_db_host: localhost
    mariadb_db_name: wordpress
    mariadb_db_user: wordpress
    mariadb_db_pwd: wordpress
    mariadb_socket_authentication: False
    wordpress_path: /var/www/html
    wordpress_conf_dir: /var/www/html
    wordpress_db_host: localhost
    wordpress_db_name: wordpress
    wordpress_db_user: wordpress
    wordpress_db_pwd: wordpress
  roles:
    - deitkrachten.showinfo
    - deitkrachten.openssl
    - deitkrachten.apache
    - deitkrachten.php
    - deitkrachten.mariadb
  tasks:
    - name: Include role 'ansible-role-wordpress'
      ansible.builtin.include_role:
        name: ansible-role-wordpress
